# Generated by Django 5.0 on 2023-12-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mangnamentuser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
